
export const ActionTypes = {

//This is for authentication 

    LOGIN_USER:"LOGIN_USER",
    LOGIN_FAILED:"LOGIN_FAILED",
    SIGNUP_USER:"SIGNUP_USER",
    SIGNUP_FAILED:"SIGNUP_FAILED",


//This is for user based 


    GET_ALL_USER:"GET_ALL_USER",
    GET_ALL_USER_FAILED:"GET_ALL_USER_FAILED",
    FETCH_USER:"FETCH_USER",
    FETCH_USER_FAILED:"FETCH_USER_FAILED",
    FETCH_USER_FRIEND:"FETCH_USER_FRIEND",
    FETCH_USER_FRIEND_FAILED:"FETCH_USER_FRIEND_FAILED",
    FOLLOW_USER : "FOLLOW_USER",
    UNFOLLOW_USER:"FOLLOW_USER",
    UPDATE_USER:"UPDATE_USER",
    UPDATE_USER_FAILED:"UPDATE_USER_FAILED",
    

// This is for posts based action
    UPLOAD_PHOTO:"UPLOAD_PHOTO",
    UPLOAD_PHOTO_FAILED:"UPLOAD_PHOTO_FAILED",
    UPDATE_PHOTO:"UPDATE_PHOTO",
    UPDATE_PHOTO_FAILED:"UPDATE_PHOTO_FAILED",

    DELETE_PHOTO:"DELETE_PHOTO",
    DELETE_PHOTO_FAILED:"DELETE_PHOTO_FAILED",
    GET_POSTS:"GET_POSTS",
    GET_POSTS_FAILED :"GET_POSTS_FAILED",
    LIKE_POST:"LIKE_POST",
    LIKE_POST_FAILED:"LIKE_POST_FAILED",
    COMMENT_POST:"COMMENT_POST",
    COMMENT_POST_FAILED:"COMMENT_POST_FAILED"
}